# This workflow deploys the main branch to Heroku https://grid-optimizer.herokuapp.com/

name: Deploy Prod @ Heroku 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - name: Install node modules
        working-directory: ./src-vue
        run: npm install
      - name: Build with Gradle
        run: gradle build
      - name: Check bundle
        run: ls ./bundle -l
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-artifact
          path: ./bundle

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
        # Update status   
      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://grid-optimizer.herokuapp.com/
          environment: "Production"
        
        # Get latest Artifact
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: server-artifact
          path: ./bundle
      - name: Check bundle
        run: ls ./bundle -l
      
        # Deploy
      - name: Dockerize and Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "grid-optimizer"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: "https://grid-optimizer.herokuapp.com/api/version"
          delay: 15
          rollbackonhealthcheckfailed: true

        # Update status
      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://grid-optimizer.herokuapp.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://grid-optimizer.herokuapp.com
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
